import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Perfeito</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Perfeito Perfeito <a href="https://nextjs.org">Perfeito</a>
        </h1>

        <p className={styles.description}>
          Perfeito Perfeito Perfeito Perfeito{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Perfeito &rarr;</h2>
            <p>Perfeito Perfeito Perfeito Perfeito Perfeito Perfeito Perfeito Perfeito.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Perfeito &rarr;</h2>
            <p>Perfeito Perfeito Perfeito.js Perfeito Perfeito Perfeito Perfeito Perfeito Perfeito!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Perfeito &rarr;</h2>
            <p>Perfeito Perfeito Perfeito Perfeito Perfeito Perfeito.js Perfeito.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Perfeito &rarr;</h2>
            <p>
              Perfeito Perfeito Perfeito Perfeito.js Perfeito Perfeito Perfeito Perfeito Perfeito Perfeito Perfeito.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Perfeito Perfeito{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
